server:
  port: 8089

spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        check_nullability: true
        temp:
          use_jdbc_metadata_defaults: false

  datasource:
    url: jdbc:postgresql://localhost:5432/monitor_sensor
    username: ${POSTGRESQL_USERNAME}
    password: ${POSTGRESQL_PASSWORD}
    driver-class-name: org.postgresql.Driver

security:
  jwt:
    secret: javasecret
